package oscar.compilador2;

/* Generated By:JavaCC: Do not edit this line. Compilador2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Compilador2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPO = 5;
  /** RegularExpression Id. */
  int OP = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int PARIZQUIERDO = 9;
  /** RegularExpression Id. */
  int PARDERECHO = 10;
  /** RegularExpression Id. */
  int LLAVEIZQUIERDA = 11;
  /** RegularExpression Id. */
  int LLAVEDERECHA = 12;
  /** RegularExpression Id. */
  int COMA = 13;
  /** RegularExpression Id. */
  int BOOLEANVALUE = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int EXTENDS = 17;
  /** RegularExpression Id. */
  int MAIN = 18;
  /** RegularExpression Id. */
  int VOID = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int ENTERO = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<TIPO>",
    "<OP>",
    "\"else\"",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<BOOLEANVALUE>",
    "\"return\"",
    "\"class\"",
    "\"extends\"",
    "\"main\"",
    "\"void\"",
    "<ID>",
    "<ENTERO>",
    "\";\"",
    "\"System.out.println\"",
    "\"=\"",
  };

}
