package oscar.compilador1;

/* Generated By:JavaCC: Do not edit this line. Oscar2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Oscar2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tipo = 5;
  /** RegularExpression Id. */
  int op = 6;
  /** RegularExpression Id. */
  int elses = 7;
  /** RegularExpression Id. */
  int ifs = 8;
  /** RegularExpression Id. */
  int parIzquierdo = 9;
  /** RegularExpression Id. */
  int parDerecho = 10;
  /** RegularExpression Id. */
  int id = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<tipo>",
    "<op>",
    "\"else\"",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "<id>",
    "\";\"",
    "\"System.out.println\"",
    "\"=\"",
  };

}
